"""
scan_extensions.py — PlatformIO pre-build script.
Scans include/extensions/ext_*.h, validates interface, generates registry.
"""
import os
import re
import sys

Import("env")  # type: ignore  # noqa: F401

EXT_DIR = os.path.join("include", "extensions")
OUT_FILE = os.path.join("include", "extensions_generated.h")

REQUIRED_FUNCS = ["_setup", "_loop", "_render"]
SCREEN_PATTERN = re.compile(r"#define\s+EXT_(\w+)_SCREEN\s+(\d+)")
FUNC_PATTERN = re.compile(r"inline\s+void\s+ext_(\w+)_setup\b")
LOOP_PATTERN = re.compile(r"inline\s+void\s+ext_(\w+)_loop\b")
RENDER_PATTERN = re.compile(r"inline\s+void\s+ext_(\w+)_render\b")


def scan_extensions():
    ext_dir = os.path.normpath(EXT_DIR)
    if not os.path.isdir(ext_dir):
        print(f"[scan_extensions] Extensions dir not found: {ext_dir}")
        return

    valid = []
    skipped = []

    for fname in sorted(os.listdir(ext_dir)):
        if not fname.startswith("ext_") or not fname.endswith(".h"):
            continue

        fpath = os.path.join(ext_dir, fname)
        with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()

        name = fname[4:-2]  # strip ext_ and .h

        # Check for screen define
        sm = SCREEN_PATTERN.search(content)
        if not sm:
            skipped.append((fname, "no EXT_*_SCREEN define"))
            continue
        screen_name = sm.group(1)
        screen_num = int(sm.group(2))

        # Check required functions
        if not FUNC_PATTERN.search(content):
            skipped.append((fname, f"no ext_{name}_setup() function"))
            continue
        if not LOOP_PATTERN.search(content):
            skipped.append((fname, f"no ext_{name}_loop() function"))
            continue
        if not RENDER_PATTERN.search(content):
            skipped.append((fname, f"no ext_{name}_render() function"))
            continue

        valid.append({
            "name": name,
            "file": fname,
            "screen_define": f"EXT_{screen_name.upper()}_SCREEN",
            "screen_num": screen_num,
        })

    # Report
    if skipped:
        print(f"\n[scan_extensions] Skipped {len(skipped)} extension(s):")
        for fname, reason in skipped:
            print(f"  SKIP  {fname} — {reason}")

    if valid:
        print(f"[scan_extensions] Found {len(valid)} extension(s):")
        for ext in valid:
            print(f"  OK    {ext['file']}  screen={ext['screen_num']}")
    else:
        print("[scan_extensions] No valid extensions found.")

    # Generate header
    lines = []
    lines.append("#pragma once")
    lines.append("// AUTO-GENERATED by scripts/scan_extensions.py — do not edit manually.")
    lines.append("")

    # Includes
    for ext in valid:
        lines.append(f'#include "extensions/{ext["file"]}"')
    lines.append("")

    # EXT_COUNT
    lines.append(f"#define EXT_COUNT {len(valid)}")
    lines.append("")

    # Setup
    lines.append("inline void extensions_setup() {")
    for ext in valid:
        lines.append(f'  ext_{ext["name"]}_setup();')
    lines.append("}")
    lines.append("")

    # Loop
    lines.append("inline void extensions_loop() {")
    for ext in valid:
        lines.append(f'  ext_{ext["name"]}_loop();')
    lines.append("}")
    lines.append("")

    # Render — dispatch by screen number
    lines.append("inline void extensions_render() {")
    lines.append("  disp.firstPage();")
    lines.append("  do {")
    for i, ext in enumerate(valid):
        keyword = "if" if i == 0 else "} else if"
        lines.append(f'    {keyword} (current_screen == {ext["screen_define"]}) {{')
        lines.append(f'      ext_{ext["name"]}_render();')
    if valid:
        lines.append("    }")
    lines.append("  } while (disp.nextPage());")
    lines.append("}")
    lines.append("")

    # Screen count
    lines.append("inline int extensions_screen_count() {")
    lines.append("  return 1 + EXT_COUNT;")
    lines.append("}")

    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[scan_extensions] Generated {OUT_FILE}")


# Run at build time
scan_extensions()
