#pragma once
// ═══════════════════════════════════════════════════════════════════════════
//  extensions.h  –  Auto-generated plug-and-play extension registry
// ═══════════════════════════════════════════════════════════════════════════
//
//  DO NOT EDIT THIS FILE. It is regenerated every build by scan_extensions.py
//
//  To add an extension: drop ext_<name>.h into include/extensions/ and rebuild.
//  To remove it: delete the file and rebuild.
//  Broken extensions are automatically excluded with a build warning.
//
// ═══════════════════════════════════════════════════════════════════════════

#include "extensions_generated.h"
