#pragma once
// AUTO-GENERATED by scripts/scan_extensions.py — do not edit manually.

#include "extensions/ext_pomodoro.h"
#include "extensions/ext_weather.h"

#define EXT_COUNT 2

inline void extensions_setup() {
  ext_pomodoro_setup();
  ext_weather_setup();
}

inline void extensions_loop() {
  ext_pomodoro_loop();
  ext_weather_loop();
}

inline void extensions_render() {
  disp.firstPage();
  do {
    if (current_screen == EXT_POMODORO_SCREEN) {
      ext_pomodoro_render();
    } else if (current_screen == EXT_WEATHER_SCREEN) {
      ext_weather_render();
    }
  } while (disp.nextPage());
}

inline int extensions_screen_count() {
  return 1 + EXT_COUNT;
}
